/*
@TargetNode='AuditAccountMaxage'
@GeneratedBy=jchancellor
@GenerationDate=07/06/2021 16:37:42
@GenerationHost=jchancellor
*/

instance of MSFT_AccountPolicy as $MSFT_AccountPolicy1ref
{
SourceInfo = "C:\\Users\\jchancellor\\maxage_script.ps1::15::7::AccountPolicy";
 ModuleName = "SecurityPolicyDsc";
 Name = "PasswordPolicies";
 Maximum_Password_Age = 60;
 ResourceID = "[AccountPolicy]AccountPolicies";
 ModuleVersion = "2.10.0.0";
 ConfigurationName = "AuditAccountMaxage";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="jchancellor";

                        GenerationDate="07/06/2021 16:37:42";

                        GenerationHost="jchancellor";

                        Name="AuditAccountMaxage";

                    };
